### ISSUE TITLE
Side car is not able to clean up block (Unsupported type of io.Reader)

### ISSUE THREAD

**Issue by mohanagandlla** [thanos-io/kube-thanos#179]
Hi 
I am using the thanos sidecar for prometheus which is from operator after the block generation the block is not uplodig success ful some irregular formates are geenerating these are the logs.

level=warn ts=2020-11-26T03:03:51.020333618Z caller=s3.go:399 msg="could not guess file size for multipart upload; upload might be not optimized" name=debug/metas/01ER17WJWGR8Z44CHR42DQW3SY.json err="unsupported type of io.Reader"
level=error ts=2020-11-26T03:04:12.102790195Z caller=shipper.go:349 msg="failed to clean upload directory" err="unlinkat /prometheus/thanos/upload/01ER17WJWGR8Z44CHR42DQW3SY/chunks: directory not empty"

**Comment by yeya24** [comment]
Hi, this issue is not related to `kube-thanos` repo, can you please open this issue on the thanos repo?

For the logs you showed:
1. I answered the question for the first log here https://github.com/thanos-io/thanos/issues/3470, it is not an error tbh

2. In this case, it just fails to clean up the upload directory so it is not a big problem and you can delete that dir manually. I think the data should be correctly uploaded, you can check that in your obj store.
