### ISSUE TITLE
Question about Service Account Name?

### ISSUE THREAD

**Issue by winshenting** [thanos-io/kube-thanos#210]
In the manifest, I see yaml about service account. What is service account used for? For description?

**Comment by metalmatze** [comment]
This seems mostly like a Kubernetes ServiceAccount question and not specifically like one for kube-thanos.
It's probably best to read the documentation by Kubernetes on Service Accounts and come back if you still have kube-thanos questions about ServiceAccounts: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/

tldr is: Each Pod has a ServiceAccount that provides and identity to the Pod so that if it queries the Kubernetes API the role-based-access-control (RBAC) can be applied appropriately.
