### ISSUE TITLE
Why query has duplicated thanos-store config

### ISSUE THREAD

**Issue by zhaojinxin409** [thanos-io/kube-thanos#236]
**yml file:** 
https://github.com/thanos-io/kube-thanos/blob/e1a68590f56034ca1a43d59401f03e72fd01ac5f/examples/all/manifests/thanos-query-deployment.yaml
**config:**
```
- args:
        - query
        - --store=dnssrv+_grpc._tcp.thanos-store.thanos.svc.cluster.local
        - --store=dnssrv+_grpc._tcp.thanos-store-0.thanos.svc.cluster.local
        - --store=dnssrv+_grpc._tcp.thanos-store-1.thanos.svc.cluster.local
        - --store=dnssrv+_grpc._tcp.thanos-store-2.thanos.svc.cluster.local
```

**Comment by yeya24** [comment]
@zhaojinxin409 Because in the `all.jsonnet` example, we create both a single store statefulset and a sharded store statefulset with 3 replicas.
Please check https://github.com/thanos-io/kube-thanos/blob/e1a68590f5/all.jsonnet#L203-L205.

This is just an example and please modify it based on your own requirement.
